import type { Metadata } from "next";
import "./globals.css";
import { TopBanner } from "@/components/shared/TopBanner";
import { Header } from "@/components/shared/header/Header";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className="bg-white font-satoshi-r text-sm">
            <TopBanner />
            <Header />
            {children}
         </body>
      </html>
   );
}
